server:
  port: 8080

spring:
  application:
    name: investment-iq-backend
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.hbbhqhyhboghwglajrlx
    password: investmentiqdb2026
    hikari:
      schema: investment_iq_dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC #to display in logs

  spring:
    jackson:
      time-zone: UTC
      write-dates-as-timestamps: false

#logging:
#  level:
#    root: INFO
#    com.investmentiq: DEBUG
#  file:
#    name: logs/investment-iq.log
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics